web/site/common/models/BugAction.php
<?php

namespace common\models;

use Yii;
use yii\db\ActiveRecord;

/**
 * This is the model class for table "bug_action".
 *
 * @property int $id
 * @property int|null $bug_id
 * @property string|null $action_type
 * @property string|null $notes
 * @property string $delete_status
 * @property int|null $created_at
 * @property int|null $created_by
 */
class BugAction extends \common\components\MyCustomActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'bug_action';
    }
    
    public function behaviors()
    {
        return [
            "timestamp" => [
                'class' => \yii\behaviors\TimestampBehavior::className(),
                'attributes' => [
                    ActiveRecord::EVENT_BEFORE_INSERT => ['created_at'],
                ],
            ],
            "blame" => [
                'class' => \yii\behaviors\BlameableBehavior::className(),
                'attributes' => [
                    ActiveRecord::EVENT_BEFORE_INSERT => ['created_by'],
                ],
            ],
            "auditTrail" => \common\behaviors\MyAuditTrailBehavior::className(),  
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['bug_id', 'created_at', 'created_by'], 'integer'],
            [['action_type', 'notes', 'delete_status'], 'string'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'bug_id' => 'Bug ID',
            'action_type' => 'Action Type',
            'notes' => 'Notes',
            'delete_status' => 'Delete Status',
            'created_at' => 'Created At',
            'created_by' => 'Created By',
        ];
    }

    /**
     * {@inheritdoc}
     * @return \common\models\query\BugActionQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\query\BugActionQuery(get_called_class());
    }

    public static function makeModel($bug_id, $action_type){
        $m = new SELF();
        $m->bug_id = $bug_id;
        $m->action_type = $action_type;

        return $m;
    }
}

web/site/backend/controllers/BugController.php
<?php

namespace backend\controllers;

use Yii;
use common\models\User;
use common\models\Bug;
use common\models\BugTag;
use common\models\BugAction;
use common\models\BugComment;
use common\models\BugDocument;
use common\models\search\BugSearch;
use common\models\search\BugCommentSearch;

use common\components\MyCustomActiveRecord;

use backend\models\BugCreationForm;
use backend\models\BugTaskForm;

use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\data\ArrayDataProvider;
use yii\filters\VerbFilter;
use yii\helpers\FileHelper;

/**
 * BugController implements the CRUD actions for Bug model.
 */
class BugController extends Controller
{

    /** @inheritdoc */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    public function actionTasks()
    {
        $searchModel = new BugSearch();

        if (Yii::$app->user->can(User::ROLE_REVIEWER)){
          $searchModel->setFilterBy([Bug::BUG_STATUS_PENDING_REVIEW]);
        } elseif (Yii::$app->user->can(User::ROLE_TRIAGER)){
          $searchModel->setFilterByNewUnassigned(true);
        } elseif (Yii::$app->user->can(User::ROLE_DEVELOPER)) {
          $searchModel->setFilterBy([Bug::BUG_STATUS_ASSIGNED, Bug::BUG_STATUS_REOPEN]);
          $searchModel->setAssignedTo(Yii::$app->user->getID());
        }

        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'page'=>'tasks',
        ]);
    }

    public function actionClosed() {
      $searchModel = new BugSearch();
      $searchModel->setFilterBy([Bug::BUG_STATUS_COMPLETED]);
      $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

      return $this->render('index', [
        'searchModel' => $searchModel,
        'dataProvider' => $dataProvider,
        'page' => 'closed',
      ]);
    }
    /**
     * Lists all Bug models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new BugSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'page'=>'index',
        ]);
    }

    /**
     * Lists bugs submitted by current user
     * @return mixed
     */
    public function actionUserSubmissions()
    {
        $searchModel = new BugSearch();
        $searchModel->setSubmittedBy(Yii::$app->user->id);
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'page' => 'user-submissions',
        ]);
    }

    /**
     * Displays a single Bug model.
     * @param integer $id
     * @return mixed
     */

    public function actionDownload($fpath){
        if(file_exists($fpath)){
            Yii::$app->response->sendFile($fpath);
        }
    }

    public function actionView($id)
    {
        $newComment = new BugComment();
        if ($newComment->load(Yii::$app->request->post()) && $newComment->save()){
          $newComment = new BugComment();
        }

        $searchModel = new BugCommentSearch();
        $searchModel->setBugId($id);
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        $taskModel = new BugTaskForm($id);

        $availableDevelopers = User::getAvailableDevelopers();

        $lifecycle = BugAction::find()->andWhere(['bug_id'=>$id])->active()->orderBy(['created_at'=>SORT_DESC])->all();

        BugCreationForm::mkUserUploadDir();
        return $this->render('view',[
          'model' => $this->findModel($id),
          'dataProvider' => $dataProvider,
          'comment' => $newComment,
          'taskModel' => $taskModel,
          'availableDevelopers' => $availableDevelopers,
          'lifecycle' => $lifecycle,
        ]);
    }

    public function actionCreateTag(){
      // check for isAjax
      if(!Yii::$app->request->isAjax){
        return $this->goBack();
      }
      $success = false;
      $model = null;
      $errors = [];

      $model = new BugTag();

      if ($model->load(Yii::$app->request->post())) {
        $success = $model->save();
      }
      if ($model->hasErrors()) {
        $errors = $model->errors;
      }
      \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
      return [
        'success' => (bool)$success,
        'model' => $model->attributes,
        'errors'=> $errors,
      ];
    }

    public function actionDeleteTag(){
      // check for isAjax
      if(!Yii::$app->request->isAjax){
        return $this->goBack();
      }
      $success = false;
      $model = null;
      $errors = [];

      if(isset(Yii::$app->request->post()['id'])){
        $model = BugTag::findOne(Yii::$app->request->post()['id']);
        if($model){
          $model->delete_status = MyCustomActiveRecord::DELETE_STATUS_DISABLED;
          $success = $model->save();
        }
      } else {
        $errors = array('id' => 'id cannot be empty');
      }

      \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
      return [
        'success' => (bool)$success,
        'model' => $model,
        'errors'=> $errors,
      ];
    }

    public function actionProcessInteraction($id = null){
      // check for id ！= null and isAjax
      if(is_null($id) || !Yii::$app->request->isAjax){
        return $this->goBack();
      }
      $success = false;
      $model = null;
      $errors = [];

      $taskModel = new BugTaskForm($id);
      if (Yii::$app->user->can(User::ROLE_REVIEWER)){
        $taskModel->scenario = User::ROLE_REVIEWER;
      } elseif (Yii::$app->user->can(User::ROLE_TRIAGER)){
        $taskModel->scenario = User::ROLE_TRIAGER;
      } elseif (Yii::$app->user->can(User::ROLE_DEVELOPER)){
        $taskModel->scenario = User::ROLE_DEVELOPER;
      }
      if($taskModel->load(Yii::$app->request->post()) && $taskModel->validate()){
        if($taskModel->process()){
          $model = $taskModel->model->toObject();
          $success = true;
        }
      }
      if($taskModel->model){
        if($taskModel->model->hasErrors()){
          $taskModel->addErrors($taskModel->model->getErrors());
        }
      }
      if($taskModel->hasErrors()){
        $errors = $taskModel->errors;
      }

      \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
      return [
        'success' => (bool)$success,
        'model' => $model,
        'errors'=> $errors,
      ];
    }

    /**
     * Creates a new Bug model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new BugCreationForm();

        if ($model->load($_POST) && $model->createBug()) {
            Yii::$app->session->setFlash('alert', [
                'options' => ['class' => 'alert-success'],
                'body' => 'Bug created successfully!'
            ]);
            return $this->redirect([ 'view', 'id' => $model->getNewBugId() ]);
        }

        BugCreationForm::mkUserUploadDir();
        return $this->render('create', [ 'model' => $model ]);
    }

    /**
     * Updates an existing Bug model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Bug model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $bug =  $this->findModel($id);
        $bug->delete_status = 'disabled';
        $bug->save();

        $tokens = explode('/', Yii::$app->request->getReferrer());
        $slug = end($tokens);
        if ($slug === 'user-submissions') {
            return $this->redirect([ $slug ]);
        }

        return $this->redirect(['index']);
    }

    /**
     * Handles ajax request for uploading bug documents
     */
    public function actionUploadFile()
    {
        if (!Yii::$app->request->isAjax) return $this->redirect(['index']);
        if (empty($_FILES['BugCreationForm'])) {
            return json_encode([ 'error' => 'No file loaded' ]);
        }

        $details = $_FILES['BugCreationForm'];
        if (isset($_POST['immediate'])) {
            return json_encode(
                BugDocument::handleAjaxImmediateUpload($details, $_POST)
            );
        } else {
            return json_encode(BugDocument::handleAjaxUpload($details));
        }
    }

    public function actionDownloadFile()
    {
        // not actually secure, but [reasons] ...
        if (!Yii::$app->request->referrer || !isset($_GET['key'])) {
            return $this->redirect(['index']);
        }

        $doc = BugDocument::findOne(intval($_GET['key']));
        $path = $doc->getFullPath();
        if(file_exists($path)){
            Yii::$app->response->sendFile($path);
        }
    }

    /**
     * Handles ajax request for removing bug documents
     */
    public function actionRemoveFile()
    {
        if (!Yii::$app->request->isAjax) return $this->redirect(['index']);

        $dir = BugCreationForm::getUserUploadDir();

web/site/backend/views/bug/_documentUpdate.php
<?php

use yii\helpers\Url;
use kartik\widgets\FileInput;

/**
* @var yii\web\View $this
* @var common\models\Bug $model
*/

$previews = $model->getDocumentPreviews();
$canEditAttachment = Yii::$app->user->id === $model->created_by;
?>

<div>
    <?= FileInput::widget([
        'name' => 'BugCreationForm[documents][]',
        'options' => [
         'multiple' => true
        ],
        'pluginOptions' => [
         'allowedFileExtensions' => [
             'jpg', 'jpeg', 'png', 'txt', 'csv', 'pdf', 'json'
         ],
         'uploadUrl' => Url::to('/bug/upload-file'),
         'uploadExtraData' => [
             'immediate' => true,
             'bug_id' => $model->id
         ],
         'maxFileCount' => 5,
         'showCancel' => false,
         'showCaption' => false,
         'showRemove' => false,
         'showUpload' => false,
         'showClose' => false,
         'showBrowse' => $canEditAttachment,
         'browseLabel' => 'Add Document',
         'dropZoneEnabled' => false,
         'initialPreview' => $previews['data'],
         'initialPreviewConfig'  => $previews['config'],
         'initialPreviewAsData' => true,
         'overwriteInitial' => false,
         'initialPreviewShowDelete' => $canEditAttachment,
         'deleteUrl' => Url::to('/bug/remove-file'),
         'initialPreviewDownloadUrl' => Url::to('/bug/download-file'),
         'msgUploadEmpty' => 'File already uploaded',
        ],
        'pluginEvents' => [
            'filebatchselected' => "function(event, files) {
                  $(this).fileinput('upload');
             }",
            'filepredelete' => "function(event) {
                return !confirm(`Are you sure you want to delete this file?`);
            }",
            // implemented to patch over buggy behaviour
            'filepreremove' => "function(event, id, index) {
                removeFile($model->id, event, id);
            }",
            'filesuccessremove' => "function(event, id) {
                removeFile($model->id, event, id);
            }",
        ],
    ]) ?>
</div>

<script type="text/javascript">
    function removeFile(bugId, event, fileId) {
        let thumbId = fileId.split('-').pop();
        if (hasUploadError(thumbId)) return;

        if (confirm(`Are you sure you want to delete this file?`)) {
            $.ajax({
                type: 'POST',
                url: '/bug/remove-file',
                data: {
                    filename: fileId.split('_').pop(),
                    immediate: true,
                    bug_id: bugId,
                }
            });
        } else {
            event.preventDefault();
        }
    }

    function hasUploadError(id) {
        return $(`[data-fileid='${id}']`).hasClass('file-preview-error');
    }
</script>

web/site/backend/views/bug/_form.php
<?php

use yii\helpers\Html;
use yii\bootstrap4\ActiveForm;
use common\models\Bug;
use common\components\MyCustomActiveRecord;

/**
 * @var yii\web\View $this
 * @var common\models\Bug $model
 * @var yii\bootstrap4\ActiveForm $form
 */
?>

<div class="bug-form">
    <?php $form = ActiveForm::begin(); ?>
        <div class="card">
            <div class="card-body">
                <?php echo $form->errorSummary($model); ?>

                <?php echo $form->field($model, 'title')->textInput(['maxlength' => true]) ?>
                <?php echo $form->field($model, 'description')->textarea(['rows' => 6]) ?>
                <?php echo $form->field($model, 'notes')->textInput(['maxlength' => true]) ?>

                <?php if (!$model->isNewRecord) : ?>
                    <?= $form->field($model, 'bug_status')->dropDownList(Bug::getAllBugStatus(),
                        [ 'prompt' => '' ]); ?>
                    <?= $form->field($model, 'priority_level')->dropDownList(
                        [ 1 , 2 , 3 ],
                        ['prompt' => '']) ?>
                    <?= $form->field($model, 'developer_user_id')->textInput() ?>
                    <?= $form->field($model, 'delete_status')->dropDownList(MyCustomActiveRecord::deleteStatuses(),['prompt' => '']) ?>
                <?php endif; ?>

            </div>
            <div class="card-footer">
                <?php echo Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
            </div>
        </div>
    <?php ActiveForm::end(); ?>
</div>

web/site/backend/views/bug/_search.php
<?php

use yii\helpers\Html;
use yii\bootstrap4\ActiveForm;

/**
 * @var yii\web\View $this
 * @var common\models\Bug $model
 * @var yii\bootstrap4\ActiveForm $form
 */
?>

<div class="bug-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?php echo $form->field($model, 'id') ?>
    <?php echo $form->field($model, 'title') ?>
    <?php echo $form->field($model, 'description') ?>
    <?php echo $form->field($model, 'bug_status') ?>
    <?php echo $form->field($model, 'priority_level') ?>
    <?php // echo $form->field($model, 'developer_user_id') ?>
    <?php // echo $form->field($model, 'notes') ?>
    <?php // echo $form->field($model, 'delete_status') ?>
    <?php // echo $form->field($model, 'created_at') ?>
    <?php // echo $form->field($model, 'created_by') ?>
    <?php // echo $form->field($model, 'updated_at') ?>
    <?php // echo $form->field($model, 'updated_by') ?>

    <div class="form-group">
        <?php echo Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?php echo Html::resetButton('Reset', ['class' => 'btn btn-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

web/site/backend/views/bug/comment.php
<?php
use common\models\User;

?>

<div class="card">
    <div class="card-body">
        <?php echo $model->comment ?>
    </div>
    <div class="card-footer">
        <div class="d-flex flex-row-reverse">
            <i><?php echo Yii::$app->formatter->asDateTime($model->created_at)?></i>
            <div class="pr-3">
                <?php echo User::findIdentity($model->created_by)->publicIdentity?>
            </div>
        </div>
    </div>
</div>

web/site/backend/views/bug/create.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\bootstrap4\ActiveForm;
use common\components\MyCustomActiveRecord;
use kartik\widgets\FileInput;
use kartik\select2\Select2;
use yii\web\JsExpression;

/**
 * @var yii\web\View $this
 * @var common\models\Bug $model
 */

$this->title = 'Create Bug';
$this->params['breadcrumbs'][] = ['label' => 'Bugs', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="bug-create">
  <div class="bug-form">
    <?php $form = ActiveForm::begin([ 'options' => ['enctype' => 'multipart/form-data'] ]); ?>
      <div class="card">

        <div class="card-body">
          <?= $form->errorSummary($model); ?>
          <?= $form->field($model, 'title')->textInput(['maxlength' => true]) ?>
          <?= $form->field($model, 'description')->textarea(['rows' => 6]) ?>

          <?= $form->field($model, 'documents[]')->widget(FileInput::classname(), [
              'options' => [
                  'multiple' => true
              ],
              'pluginOptions' => [
                  'allowedFileExtensions' => [
                      'jpg', 'jpeg', 'png', 'txt', 'csv', 'json', 'pdf'
                  ],
                  'uploadUrl' => Url::to('/bug/upload-file'),
                  'maxFileCount' => 5,
                  'showCancel' => false,
                  'showCaption' => false,
                  'showRemove' => false,
                  'showUpload' => false,
                  'dropZoneEnabled' => false,
              ],
              'pluginEvents' => [
                  'filebatchselected' => "function(event) {
                      $(this).fileinput('upload');
                  }",
                  'fileremoved' => "function(event, id, index) {
                       $.ajax({
                           type: 'POST',
                           url: '/bug/remove-file',
                           data: { filename: id.split('_').pop() }
                       });
                   }",
                  'fileclear' => "function(event) {
                      $.ajax({
                          type: 'POST',
                          url: '/bug/remove-file',
                          data: { delete_all: true }
                      });
                  }",
              ],
          ]) ?>

          <?= $form->field($model, 'tags')->widget(Select2::classname(),
              [
                  'theme' => Select2::THEME_MATERIAL,
                  'data' => $model->getCommonTags(),
                  'showToggleAll' => false,
                  'options' => [
                      'placeholder' => 'Select common tags or add your own ...',
                      'multiple' => true,
                  ],
                  'pluginOptions' => [
                      'tags' => true,
                      'tokenSeparators' => [ ',', ' ' ],
                      'maximumInputLength' => 15,
                      'allowClear' => true,
                      'createTag' => new JsExpression("function({ term, data }) {
                           return { id: term.toLowerCase(), text: term.toLowerCase() };
                       }")
                  ],
              ]
            ); ?>
        </div>

        <div class="card-footer">
          <?= Html::submitButton('Create', ['class' => 'btn btn-success'])?>
        </div>

      </div>
    <?php ActiveForm::end(); ?>
  </div>
</div>

web/site/backend/views/bug/index.php
<?php

use yii\helpers\Url;
use yii\helpers\Html;
use yii\grid\GridView;
use common\models\Bug;
use common\models\User;

/**
 * @var yii\web\View $this
 * @var common\models\search\BugSearch $searchModel
 * @var yii\data\ActiveDataProvider $dataProvider
 */

$this->title = 'Bugs';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="bug-index">
    <div class="card">
        <?php
            if (Yii::$app->user->can(User::ROLE_DEVELOPER) || Yii::$app->user->can(User::ROLE_TRIAGER) || Yii::$app->user->can(User::ROLE_REVIEWER)){
                echo \backend\widgets\TabMenuBugWithTaskWidget::widget(['page'=>$page]);
            } else {
                echo \backend\widgets\TabMenuBugWidget::widget(['page'=>$page]);
            }
        ?>
        <div class="card-header">
            <?php echo Html::a('Create Bug', ['create'], ['class' => 'btn btn-success']) ?>
            <!-- <?php echo Html::a('All Bugs', ['index'], ['class' => 'btn btn-success']) ?> -->
            <!-- <?php echo Html::a('My Tasks', ['tasks'], ['class' => 'btn btn-success']) ?> -->
        </div>

        <div class="card-body p-0">
            <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

            <?php echo GridView::widget([
                'layout' => "{items}\n{pager}",
                'options' => [
                    'class' => ['gridview', 'table-responsive'],
                ],
                'tableOptions' => [
                    'class' => ['table', 'text-nowrap', 'table-striped', 'table-bordered', 'mb-0'],
                ],
                'dataProvider' => $dataProvider,
                'filterModel' => $searchModel,
                'columns' => [
                    // ['class' => 'yii\grid\SerialColumn'],

                    'id',
                    [
                        'attribute'=>'title',
                        'format'=>'raw',
                        'value'=> function($model){
                            return Html::a($model->title, Url::to(['view','id'=>$model->id]));
                        }
                    ],
                    //'description:ntext',
                    'bug_status',
                    'priority_level',
                    [
                        'attribute'=>'created_at',
                        'format'=>'raw',
                        'value'=> function($model){
                            return Yii::$app->formatter->asDateTime($model->created_at);
                        }
                    ],
                    // 'developer_user_id',
                    // 'notes',
                    // 'delete_status',
                    // 'created_at',
                    // 'created_by',
                    // 'updated_at',
                    // 'updated_by',
                    [
                        'class' => \common\widgets\ActionColumn::class,
                        'template' => '{delete}',
                        'visibleButtons' => [
                            'delete' => function($model, $key, $index) {
                                return $model->created_by === Yii::$app->user->id &&
                                       $model->bug_status === Bug::BUG_STATUS_NEW;
                            }
                        ],
                    ],
                ],
            ]); ?>

        </div>
        <div class="card-footer">
            <?php echo getDataProviderSummary($dataProvider) ?>
        </div>
    </div>

</div>

web/site/backend/views/bug/update.php
<?php

/**
 * @var yii\web\View $this
 * @var common\models\Bug $model
 */

$this->title = 'Update Bug: ' . ' ' . $model->title;
$this->params['breadcrumbs'][] = ['label' => 'Bugs', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->title, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="bug-update">

    <?php echo $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>